export const __cookieName__: string = "qid";
export const __cookieMaxAge__: number = 1000 * 60 * 60 * 24 * 7; // 7 days

export enum Events {
  ON_AUTH_STATE_CHANGED = "ON_AUTH_STATE_CHANGED",
  ON_ENGINES_STATE_CHANGE = "ON_ENGINES_STATE_CHANGE",
}

export const CARDS = [
  { id: "A_OF_HEARTS", index: 0, value: "A" },
  { id: "A_OF_SPADES", index: 1, value: "A" },
  { id: "A_OF_DIAMONDS", index: 2, value: "A" },
  { id: "A_OF_CLUBS", index: 3, value: "A" },
  { id: "2_OF_HEARTS", index: 0, value: 2 },
  { id: "2_OF_SPADES", index: 1, value: 2 },
  { id: "2_OF_DIAMONDS", index: 2, value: 2 },
  { id: "2_OF_CLUBS", index: 3, value: 2 },
  { id: "3_OF_HEARTS", index: 0, value: 3 },
  { id: "3_OF_SPADES", index: 1, value: 3 },
  { id: "3_OF_DIAMONDS", index: 2, value: 3 },
  { id: "3_OF_CLUBS", index: 3, value: 3 },
  { id: "4_OF_HEARTS", index: 0, value: 4 },
  { id: "4_OF_SPADES", index: 1, value: 4 },
  { id: "4_OF_DIAMONDS", index: 2, value: 4 },
  { id: "4_OF_CLUBS", index: 3, value: 4 },
  { id: "5_OF_HEARTS", index: 0, value: 5 },
  { id: "5_OF_SPADES", index: 1, value: 5 },
  { id: "5_OF_DIAMONDS", index: 2, value: 5 },
  { id: "5_OF_CLUBS", index: 3, value: 5 },
  { id: "6_OF_HEARTS", index: 0, value: 6 },
  { id: "6_OF_SPADES", index: 1, value: 6 },
  { id: "6_OF_DIAMONDS", index: 2, value: 6 },
  { id: "6_OF_CLUBS", index: 3, value: 6 },
  { id: "7_OF_HEARTS", index: 0, value: 7 },
  { id: "7_OF_SPADES", index: 1, value: 7 },
  { id: "7_OF_DIAMONDS", index: 2, value: 7 },
  { id: "7_OF_CLUBS", index: 3, value: 7 },
  { id: "8_OF_HEARTS", index: 0, value: 8 },
  { id: "8_OF_SPADES", index: 1, value: 8 },
  { id: "8_OF_DIAMONDS", index: 2, value: 8 },
  { id: "8_OF_CLUBS", index: 3, value: 8 },
  { id: "9_OF_HEARTS", index: 0, value: 9 },
  { id: "9_OF_SPADES", index: 1, value: 9 },
  { id: "9_OF_DIAMONDS", index: 2, value: 9 },
  { id: "9_OF_CLUBS", index: 3, value: 9 },
  { id: "10_OF_HEARTS", index: 0, value: 10 },
  { id: "10_OF_SPADES", index: 1, value: 10 },
  { id: "10_OF_DIAMONDS", index: 2, value: 10 },
  { id: "10_OF_CLUBS", index: 3, value: 10 },
  { id: "K_OF_HEARTS", index: 0, value: "K" },
  { id: "K_OF_SPADES", index: 1, value: "K" },
  { id: "K_OF_DIAMONDS", index: 2, value: "K" },
  { id: "K_OF_CLUBS", index: 3, value: "K" },
  { id: "Q_OF_HEARTS", index: 0, value: "Q" },
  { id: "Q_OF_SPADES", index: 1, value: "Q" },
  { id: "Q_OF_DIAMONDS", index: 2, value: "Q" },
  { id: "Q_OF_CLUBS", index: 3, value: "Q" },
  { id: "J_OF_HEARTS", index: 0, value: "J" },
  { id: "J_OF_SPADES", index: 1, value: "J" },
  { id: "J_OF_DIAMONDS", index: 2, value: "J" },
  { id: "J_OF_CLUBS", index: 3, value: "J" },
  { id: "BLACK_JOCKEY", index: 1, value: "JOCKEY" },
  { id: "RED_JOCKEY", index: 2, value: "JOCKEY" },
].map((card) => ({ ...card, value: card.value.toString() }));
